config/routes.rb
UTUOnRails::Application.routes.draw do
  resources :exams

  resources :tasks

  resources :events

  root to: 'summary#summary', as: 'utu'
  
  get 'details' => 'summary#details'

end

app/models/event.rb
class DateValidator < ActiveModel::Validator
  def validate(record)
    if record.end < record.start
      record.errors.add(:end, 'musí být později než začátek akce')
    end
  end
end

class Event < ActiveRecord::Base
  validates :title, :description, :start, :end, :location, presence: {presence: true, message: "nesmí být prázdný"}
  validates_with DateValidator
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  SUBJECTS = ["MA", "F", "ČJL", "HV", "VV", "IKT", "D", "VO", "NJ", "AJ", "TV", "PŘÍ"]
  validates :title, :description, :subject, :group, :date, presence: {presence: true, message: "nesmí být prázdný"}
  validates :subject, inclusion: {in: SUBJECTS, message: "není platný předmět"}
  validates :group, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 2, only_integer: true, message: "neexistuje" }
end

app/models/task.rb
class Task < ActiveRecord::Base
  SUBJECTS = ["MA", "F", "ČJL", "HV", "VV", "IKT", "D", "VO", "NJ", "AJ", "TV", "PŘÍ"]
  validates :title, :description, :subject, :group, :date, presence: {presence: true, message: "nesmí být prázdný"}
  validates :subject, inclusion: {in: SUBJECTS, message: "není platný předmět"}
  validates :group, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 2, only_integer: true, message: "neexistuje - zadejte 0 pro obě skupiny" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :location, :start, :end)
    end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]

  # GET /exams
  # GET /exams.json
  def index
    @exams = Exam.all
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  # GET /exams/new
  def new
    @exam = Exam.new
  end

  # GET /exams/1/edit
  def edit
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Exam was successfully created.' }
        format.json { render action: 'show', status: :created, location: @exam }
      else
        format.html { render action: 'new' }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to @exam, notice: 'Exam was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { redirect_to exams_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(:title, :description, :subject, :date, :group)
    end
end

app/controllers/summary_controller.rb
class SummaryController < ApplicationController
  def summary
    events = []
    Event.all.each do |i|
      if i.end > Time.now
        events.push(i)        
      end
    end
    @events = events
    
    exams = []
    Exam.all.each do |i|
      if i.date > Time.now
        exams.push(i)        
      end
    end
    @exams = exams
    
    tasks = []
    Task.all.each do |i|
      if i.date > Time.now
        tasks.push(i)        
      end
    end
    @tasks = tasks
  end
  def details
    events = []
    Event.all.each do |i|
      if i.end > Time.now
        events.push(i)        
      end
    end
    @events = events
    
    exams = []
    Exam.all.each do |i|
      if i.date > Time.now
        exams.push(i)        
      end
    end
    @exams = exams
    
    tasks = []
    Task.all.each do |i|
      if i.date > Time.now
        tasks.push(i)        
      end
    end
    @tasks = tasks
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :subject, :date, :group)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/summary_helper.rb
module SummaryHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/application/_menu.html.erb
<ul>
    <li>
        <%= link_to("Přehled", utu_path) %>
    </li>
    <li>
        <%= link_to("Podrobnosti", details_path) %>
    </li>
    <li>
        <%= link_to("Události", events_path) %>
    </li>
    <li>
        <%= link_to("Úkoly", tasks_path) %>
    </li>
    <li>
        <%= link_to("Testy", exams_path) %>
    </li>
</ul>
<script>
    $("li").bind("mouseenter", function() {
        $(this).children().css("borderBottom", "1px solid white")
        $(this).children().animate({
        }, 1000);
    });
    $("li").bind("mouseleave", function() {
        $(this).children().css("borderWidth", "0px")
        $(this).children().animate({
        }, 1000);
    });
</script>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, 'Název' %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description, 'Popis' %><br>
    <%= f.text_field :description, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label :location, 'Místo' %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :start, 'Počátek akce' %><br>
    <%= f.date_select :start %>
  </div>
  <div class="field">
    <%= f.label :end, 'Konec akce' %><br>
    <%= f.date_select :end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Location</th>
      <th>Start</th>
      <th>End</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.location %></td>
        <td><%= event.start %></td>
        <td><%= event.end %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Start:</strong>
  <%= @event.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @event.end %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/exams/_form.html.erb
<%= form_for(@exam) do |f| %>
  <% if @exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
      <% @exam.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, 'Název' %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description, 'Popis' %><br>
    <%= f.text_area :description, rows: 6, cols: 30 %>
  </div>
  <div class="field">
    <%= f.label :subject, 'Předmět' %><br>
    <%= f.select :subject, Exam::SUBJECTS, prompt: "Zvolte předmět" %>
  </div>
  <div class="field">
    <%= f.label :date, 'Datum splnění' %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :group, 'Skupina' %><br>
    <%= f.number_field :group %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<h1>Editing exam</h1>

<%= render 'form' %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

app/views/exams/index.html.erb
<h1>Listing exams</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Subject</th>
      <th>Date</th>
      <th>Group</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @exams.each do |exam| %>
      <tr>
        <td><%= exam.title %></td>
        <td><%= exam.description %></td>
        <td><%= exam.subject %></td>
        <td><%= exam.date %></td>
        <td><%= exam.group %></td>
        <td><%= link_to 'Show', exam %></td>
        <td><%= link_to 'Edit', edit_exam_path(exam) %></td>
        <td><%= link_to 'Destroy', exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exam', new_exam_path %>

app/views/exams/new.html.erb
<h1>New exam</h1>

<%= render 'form' %>

<%= link_to 'Back', exams_path %>

app/views/exams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @exam.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @exam.description %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @exam.subject %>
</p>

<p>
  <strong>Date:</strong>
  <%= @exam.date %>
</p>

<p>
  <strong>Group:</strong>
  <%= @exam.group %>
</p>

<%= link_to 'Edit', edit_exam_path(@exam) %> |
<%= link_to 'Back', exams_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>UTU on Rails</title>
        <%= favicon_link_tag 'favicon.ico' %>
        <%= stylesheet_link_tag 'utu' %>
        <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
        <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <div id="background">
            <div id="summary">
                <div id="header">
                    
                    <h1><%= @page_title || "UTU" %></h1>
                </div>

                <div id="menu">
                    <%= render 'menu' %>
                </div>

                <div id="main">
                    <%= yield %>
                </div>

                <div id="footer">

                </div>
            </div>
        </div>
    </body>
</html>

app/views/summary/details.html.erb
<h1>Podrobný přehled</h1>

<div id="details">
    <div class="details_block">
        <h2>Události</h2>
        <% @events.each do |e| %>

        <h3><%= e.title %></h3>
        <p>
            <%= sanitize(e.description) %>
        </p>

        <p>
            <strong>Místo: </strong>
            <%= e.location %>
        </p>

        <p>
            <strong>Začátek události: </strong>
            <%= e.start %>
        </p>

        <p>
            <strong>Konec události: </strong>
            <%= e.end %>
        </p>
        <hr class="line_between_details" />
        <% end %>
    </div>

    <div class="details_block">
        <h2>Úkoly</h2>
        <% @tasks.each do |e| %>

        <h3><%= e.title %></h3>
        <p>
            <%= sanitize(e.description) %>
        </p>

        <p>
            <strong>Předmět: </strong>
            <%= e.subject %>
        </p>

        <p>
            <strong>Datum: </strong>
            <%= e.date %>
        </p>

        <p>
            <strong>Skupina: </strong>
            <% if e.group == 0 %>
            obě skupiny
            <% else %>
            <%= e.group %>.
            <% end %>
        </p>
        <hr class="line_between_details" />
        <% end %>
    </div>

    <div class="details_block">
        <h2>Testy</h2>
        <% @exams.each do |e| %>

        <h3><%= e.title %></h3>
        <p>
            <%= sanitize(e.description) %>
        </p>

        <p>
            <strong>Předmět: </strong>
            <%= e.subject %>
        </p>

        <p>
            <strong>Datum: </strong>
            <%= e.date %>
        </p>

        <p>
            <strong>Skupina: </strong>
            <% if e.group == 0 %>
            obě skupiny
            <% else %>
            <%= e.group %>.
            <% end %>
        </p>
        <hr class="line_between_details"/>
        <% end %>
    </div>
</div>

app/views/summary/summary.html.erb
<h1>Vše je dočasné, ale už se to pomalu rýsuje :)</h1>
<p>položky v menu (události, úkoly a testy) budou později odstraněny a přístupné pouze z administrace (speciální účet)</p>
<div id="events">
	<h2>Události</h2>
	<% @events.each do |event| %>
	<div class="line_item">
		<h3><%= event.title %></h3>
		<%= sanitize(event.description) %>
		<br />
		<%= event.location %> 
	</div>
	<% end %>
</div>

<div id="tasks">
	
</div>

<div id="exams">
	
</div>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, 'Název' %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description, 'Popis' %><br>
    <%= f.text_area :description, rows: 6, cols: 30 %>
  </div>
  <div class="field">
    <%= f.label :subject, 'Předmět' %><br>
    <%= f.select :subject, Exam::SUBJECTS, prompt: "Zvolte předmět" %>
  </div>
  <div class="field">
    <%= f.label :date, 'Datum splnění' %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :group, 'Skupina' %><br>
    <%= f.number_field :group %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Subject</th>
      <th>Date</th>
      <th>Group</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.subject %></td>
        <td><%= task.date %></td>
        <td><%= task.group %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @task.subject %>
</p>

<p>
  <strong>Date:</strong>
  <%= @task.date %>
</p>

<p>
  <strong>Group:</strong>
  <%= @task.group %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>